# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qtdesigner-ui/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setDockNestingEnabled(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_tabs = QtWidgets.QTabWidget(self.centralwidget)
        self.widget_tabs.setObjectName("widget_tabs")
        self.tab_keys = QtWidgets.QWidget()
        self.tab_keys.setObjectName("tab_keys")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_keys)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.view_keys = QtWidgets.QTableView(self.tab_keys)
        self.view_keys.setAlternatingRowColors(True)
        self.view_keys.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.view_keys.setShowGrid(False)
        self.view_keys.setSortingEnabled(True)
        self.view_keys.setWordWrap(False)
        self.view_keys.setCornerButtonEnabled(False)
        self.view_keys.setObjectName("view_keys")
        self.view_keys.horizontalHeader().setDefaultSectionSize(150)
        self.view_keys.verticalHeader().setDefaultSectionSize(20)
        self.view_keys.verticalHeader().setMinimumSectionSize(20)
        self.verticalLayout.addWidget(self.view_keys)
        self.widget_tabs.addTab(self.tab_keys, "")
        self.tab_head = QtWidgets.QWidget()
        self.tab_head.setObjectName("tab_head")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_head)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.view_head = QtWidgets.QTreeView(self.tab_head)
        self.view_head.setUniformRowHeights(True)
        self.view_head.setSortingEnabled(True)
        self.view_head.setObjectName("view_head")
        self.view_head.header().setDefaultSectionSize(150)
        self.view_head.header().setStretchLastSection(False)
        self.verticalLayout_2.addWidget(self.view_head)
        self.widget_tabs.addTab(self.tab_head, "")
        self.horizontalLayout.addWidget(self.widget_tabs)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setObjectName("menubar")
        self.menu_file = QtWidgets.QMenu(self.menubar)
        self.menu_file.setObjectName("menu_file")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_open = QtWidgets.QAction(MainWindow)
        self.action_open.setObjectName("action_open")
        self.action_exit = QtWidgets.QAction(MainWindow)
        self.action_exit.setObjectName("action_exit")
        self.action_refresh = QtWidgets.QAction(MainWindow)
        self.action_refresh.setObjectName("action_refresh")
        self.menu_file.addAction(self.action_open)
        self.menu_file.addAction(self.action_refresh)
        self.menu_file.addAction(self.action_exit)
        self.menubar.addAction(self.menu_file.menuAction())

        self.retranslateUi(MainWindow)
        self.widget_tabs.setCurrentIndex(0)
        self.action_exit.triggered.connect(MainWindow.close)
        self.action_refresh.triggered.connect(MainWindow.refresh_repo)
        self.action_open.triggered.connect(MainWindow.open_repo)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Git-Annex Metadata Gui"))
        self.widget_tabs.setTabText(self.widget_tabs.indexOf(self.tab_keys), _translate("MainWindow", "All Keys"))
        self.widget_tabs.setTabText(self.widget_tabs.indexOf(self.tab_head), _translate("MainWindow", "Work Tree"))
        self.menu_file.setTitle(_translate("MainWindow", "&File"))
        self.action_open.setText(_translate("MainWindow", "&Open"))
        self.action_open.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.action_exit.setText(_translate("MainWindow", "E&xit"))
        self.action_exit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.action_refresh.setText(_translate("MainWindow", "&Refresh"))
        self.action_refresh.setShortcut(_translate("MainWindow", "F5"))

